<a href="https://colab.research.google.com/github/springboardmentor3010s/ClimateScope/blob/siddhant-268/climateScope.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
## the data reading part
cs = pd.read_csv('/content/drive/MyDrive/infosys project/GlobalWeatherRepository.csv')

In [3]:
cs.shape

(122576, 41)

In [4]:
cs.head(10)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55
5,Antigua and Barbuda,Saint John's,17.12,-61.85,America/Antigua,1715849100,2024-05-16 04:45,26.0,78.8,Partly cloudy,...,1.2,4.5,1,1,05:36 AM,06:32 PM,01:05 PM,01:14 AM,Waxing Gibbous,55
6,Argentina,Buenos Aires,-34.59,-58.67,America/Argentina/Buenos_Aires,1715849100,2024-05-16 05:45,8.0,46.4,Clear,...,4.0,5.3,1,1,07:43 AM,05:59 PM,02:36 PM,01:04 AM,Waxing Gibbous,55
7,Armenia,Yerevan,40.18,44.51,Asia/Yerevan,1715849100,2024-05-16 12:45,19.0,66.2,Partly cloudy,...,0.8,0.9,1,1,05:45 AM,08:12 PM,01:17 PM,02:31 AM,Waxing Gibbous,55
8,Australia,Canberra,-35.28,149.22,Australia/Sydney,1715849100,2024-05-16 18:45,9.0,48.2,Clear,...,3.7,5.4,1,1,06:52 AM,05:07 PM,01:31 PM,No moonset,Waxing Gibbous,55
9,Austria,Vienna,48.20,16.37,Europe/Vienna,1715849100,2024-05-16 10:45,16.0,60.8,Partly cloudy,...,3.7,4.4,1,1,05:14 AM,08:29 PM,01:00 PM,02:42 AM,Waxing Gibbous,55

In [24]:
cs['last_updated'] = pd.to_datetime(cs['last_updated'])
cs['sunrise'] = pd.to_datetime(cs['sunrise'])
cs['sunset'] = pd.to_datetime(cs['sunset'])
cs['moonrise'] = pd.to_datetime(cs['moonrise'])
cs['moonset'] = pd.to_datetime(cs['moonset'])
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122576 entries, 0 to 122575
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122576 non-null  object
 1   location_name                 122576 non-null  object
 2   latitude                      122576 non-null  float64
 3   longitude                     122576 non-null  float64
 4   timezone                      122576 non-null  object
 5   last_updated_epoch            122576 non-null  int64
 6   last_updated                  122576 non-null  datetime64[ns]
 7   temperature_celsius           122576 non-null  float64
 8   temperature_fahrenheit        122576 non-null  float64
 9   condition_text                122576 non-null  object
 10  wind_mph                      122576 non-null  float64
 11  wind_kph                      122576 non-null  float64
 12  wind_degree                   122576 non-null  int64
 13  wind_direction                122576 non-null  object
 14  pressure_mb                   122576 non-null  float64
 15  pressure_in                   122576 non-null  float64
 16  precip_mm                     122576 non-null  float64
 17  precip_in                     122576 non-null  float64
 18  humidity                      122576 non-null  int64
 19  cloud                         122576 non-null  int64
 20  feels_like_celsius            122576 non-null  float64
 21  feels_like_fahrenheit         122576 non-null  float64
 22  visibility_km                 122576 non-null  float64
 23  visibility_miles              122576 non-null  float64
 24  uv_index                      122576 non-null  float64
 25  gust_mph                      122576 non-null  float64
 26  gust_kph                      122576 non-null  float64
 27  air_quality_Carbon_Monoxide   122576 non-null  float64
 28  air_quality_Ozone             122576 non-null  float64
 29  air_quality_Nitrogen_dioxide  122576 non-null  float64
 30  air_quality_Sulphur_dioxide   122576 non-null  float64
 31  air_quality_PM2.5             122576 non-null  float64
 32  air_quality_PM10              122576 non-null  float64
 33  air_quality_us-epa-index      122576 non-null  int64
 34  air_quality_gb-defra-index    122576 non-null  int64
 35  sunrise                       122576 non-null  datetime64[ns]
 36  sunset                        122576 non-null  datetime64[ns]
 37  moonrise                      118492 non-null  datetime64[ns]
 38  moonset                       118495 non-null  datetime64[ns]
 39  moon_phase                    122576 non-null  object
 40  moon_illumination             122576 non-null  int64
dtypes: datetime64[ns](5), float64(23), int64(7), object(6)
memory usage: 38.3+ MB

In [28]:
cs['sunrise'] = cs['sunrise'].astype(str)
cs['sunset'] = cs['sunset'].astype(str)
cs['moonrise'] = cs['moonrise'].astype(str)
cs['moonset'] = cs['moonset'].astype(str)
cs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122576 entries, 0 to 122575
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122576 non-null  object
 1   location_name                 122576 non-null  object
 2   latitude                      122576 non-null  float64
 3   longitude                     122576 non-null  float64
 4   timezone                      122576 non-null  object
 5   last_updated_epoch            122576 non-null  int64
 6   last_updated                  122576 non-null  datetime64[ns]
 7   temperature_celsius           122576 non-null  float64
 8   temperature_fahrenheit        122576 non-null  float64
 9   condition_text                122576 non-null  object
 10  wind_mph                      122576 non-null  float64
 11  wind_kph                      122576 non-null  float64
 12  wind_degree                   122576 non-null  int64
 13  wind_direction                122576 non-null  object
 14  pressure_mb                   122576 non-null  float64
 15  pressure_in                   122576 non-null  float64
 16  precip_mm                     122576 non-null  float64
 17  precip_in                     122576 non-null  float64
 18  humidity                      122576 non-null  int64
 19  cloud                         122576 non-null  int64
 20  feels_like_celsius            122576 non-null  float64
 21  feels_like_fahrenheit         122576 non-null  float64
 22  visibility_km                 122576 non-null  float64
 23  visibility_miles              122576 non-null  float64
 24  uv_index                      122576 non-null  float64
 25  gust_mph                      122576 non-null  float64
 26  gust_kph                      122576 non-null  float64
 27  air_quality_Carbon_Monoxide   122576 non-null  float64
 28  air_quality_Ozone             122576 non-null  float64
 29  air_quality_Nitrogen_dioxide  122576 non-null  float64
 30  air_quality_Sulphur_dioxide   122576 non-null  float64
 31  air_quality_PM2.5             122576 non-null  float64
 32  air_quality_PM10              122576 non-null  float64
 33  air_quality_us-epa-index      122576 non-null  int64
 34  air_quality_gb-defra-index    122576 non-null  int64
 35  sunrise                       122576 non-null  object
 36  sunset                        122576 non-null  object
 37  moonrise                      122576 non-null  object
 38  moonset                       122576 non-null  object
 39  moon_phase                    122576 non-null  object
 40  moon_illumination             122576 non-null  int64
dtypes: datetime64[ns](1), float64(23), int64(7), object(10)
memory usage: 38.3+ MB

In [10]:
cs.describe(include ='all')

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
count,122576,122576,122576.000000,122576.000000,122576,1.225760e+05,122576,122576.000000,122576.000000,122576,...,122576.000000,122576.000000,122576.000000,122576.000000,122576,122576,122576,122576,122576,122576.000000
unique,211,256,NaN,NaN,198,NaN,20691,NaN,NaN,49,...,NaN,NaN,NaN,NaN,492,547,1441,1441,8,NaN
top,Bulgaria,Kabul,NaN,NaN,Asia/Bangkok,NaN,2026-01-23 08:15,NaN,NaN,Partly cloudy,...,NaN,NaN,NaN,NaN,05:57 AM,06:02 PM,No moonrise,No moonset,Waxing Gibbous,NaN
freq,1441,630,NaN,NaN,2298,NaN,45,NaN,NaN,36403,...,NaN,NaN,NaN,NaN,1297,1220,4084,4081,26931,NaN
mean,NaN,NaN,19.191038,21.996451,NaN,1.743124e+09,NaN,21.702574,71.066384,NaN,...,24.694333,49.399417,1.713158,2.641643,NaN,NaN,NaN,NaN,NaN,49.932352
std,NaN,NaN,24.427963,65.792124,NaN,1.573369e+07,NaN,9.521555,17.138671,NaN,...,38.050908,152.348830,0.952670,2.478245,NaN,NaN,NaN,NaN,NaN,35.116175
min,NaN,NaN,-41.300000,-175.200000,NaN,1.715849e+09,NaN,-29.800000,-21.600000,NaN,...,0.168000,-1848.150000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,3.750000,-6.836100,NaN,1.729502e+09,NaN,16.300000,61.400000,NaN,...,7.150000,10.100000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,15.000000
50%,NaN,NaN,17.250000,23.316700,NaN,1.743155e+09,NaN,24.100000,75.400000,NaN,...,14.350000,20.350000,1.000000,2.000000,NaN,NaN,NaN,NaN,NaN,50.000000
75%,NaN,NaN,40.400000,50.580000,NaN,1.756714e+09,NaN,28.100000,82.600000,NaN,...,28.305000,42.365000,2.000000,3.000000,NaN,NaN,NaN,NaN,NaN,85.000000
max,NaN,NaN,64.150000,179.220000,NaN,1.770360e+09,NaN,49.200000,120.600000,NaN,...,1614.100000,6037.290000,6.000000,10.000000,NaN,NaN,NaN,NaN,NaN,100.000000

In [7]:
## Know going to checkout the Null, duplicate and Error values
cs.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [8]:
cs.duplicated().sum()

np.int64(0)

In [9]:
## value count _with unique_values
for i in cs.columns:
  print(i)
  print(cs[i].value_counts())

country
country
Bulgaria         1441
Indonesia        1261
Sudan            1258
Thailand         1257
Turkey           1257
                 ...
Saudi Arabien       1
Bélgica             1
Turkménistan        1
火鸡                  1
Jemen               1
Name: count, Length: 211, dtype: int64
location_name
location_name
Kabul                   630
Tirana                  630
Andorra La Vella        630
Luanda                  630
Yerevan                 630
                       ...
Krasnyy Turkmenistan      1
Morocco City              1
Kiyabo                    1
Moldova                   1
City Of San Marino        1
Name: count, Length: 256, dtype: int64
latitude
latitude
 41.90    768
 12.15    767
 40.40    767
 5.55     630
-41.30    630
         ...
 10.75      1
 4.17       1
-7.25       1
 42.67      1
 59.89      1
Name: count, Length: 396, dtype: int64
longitude
longitude
-58.1667     975
 12.4500     766
-8.0000      631
 21.0000     630
 159.9500    630
            ...
-57.6700       1
-109.9300      1
 21.6200       1
 1.2200        1
 118.3700      1
Name: count, Length: 401, dtype: int64
timezone
timezone
Asia/Bangkok        2298
Europe/Rome         1406
Europe/Sofia        1405
America/La_Paz      1276
Asia/Jakarta        1261
                    ...
Asia/Kuching           1
America/Chicago        1
America/New_York       1
America/Denver         1
Africa/Tripoli         1
Name: count, Length: 198, dtype: int64
last_updated_epoch
last_updated_epoch
1769756400    195
1769842800    195
1769929200    195
1770015600    195
1770188400    195
             ...
1721565900      1
1767337200      1
1719838800      1
1719753300      1
1716301800      1
Name: count, Length: 1169, dtype: int64
last_updated
last_updated
2026-01-23 08:15    45
2026-02-02 08:00    45
2026-01-03 08:00    45
2026-01-02 08:15    45
2026-01-05 08:15    45
                    ..
2024-05-16 11:00     1
2024-05-16 18:30     1
2024-05-16 01:45     1
2024-05-16 14:30     1
2026-02-05 10:30     1
Name: count, Length: 20691, dtype: int64
temperature_celsius
temperature_celsius
 26.3    1632
 25.1    1629
 25.3    1615
 26.2    1613
 25.2    1605
         ...
-23.6       1
-19.1       1
-26.9       1
-18.5       1
-8.1        1
Name: count, Length: 697, dtype: int64
temperature_fahrenheit
temperature_fahrenheit
 77.2    1519
 77.5    1497
 77.4    1496
 79.3    1491
 79.2    1467
         ...
-21.6       1
 18.2       1
 17.2       1
-3.7        1
 13.3       1
Name: count, Length: 1154, dtype: int64
condition_text
condition_text
Partly cloudy                                  36403
Sunny                                          35959
Patchy rain nearby                             10094
Partly Cloudy                                   7194
Overcast                                        6497
Clear                                           5923
Mist                                            4885
Light rain                                      3837
Light rain shower                               2833
Fog                                             1448
Cloudy                                          1362
Moderate or heavy rain with thunder             1026
Moderate rain                                    968
Patchy light rain with thunder                   756
Light drizzle                                    596
Light snow                                       422
Patchy light drizzle                             410
Moderate or heavy rain shower                    273
Thundery outbreaks in nearby                     236
Patchy light rain                                218
Freezing fog                                     191
Patchy light rain in area with thunder           183
Moderate rain at times                           113
Heavy snow                                       100
Light freezing rain                               78
Patchy light snow                                 78
Moderate snow                                     75
Heavy rain                                        58
Light snow showers                                57
Light sleet                                       48
Moderate or heavy snow showers                    44
Patchy rain possible                              41
Blowing snow                                      31
Thundery outbreaks possible                       27
Patchy heavy snow                                 25
Heavy rain at times                               13
Torrential rain shower                            12
Patchy moderate snow                              11
Moderate or heavy rain in area with thunder       10
Light sleet showers                                8
Blizzard                                           7
Patchy light snow in area with thunder             5
Freezing drizzle                                   5
Moderate or heavy sleet                            4
Patchy snow possible                               4
Patchy snow nearby                                 3
Moderate or heavy snow in area with thunder        3
Moderate or heavy freezing rain                    1
Heavy freezing drizzle                             1
Name: count, dtype: int64
wind_mph
wind_mph
2.2     13724
4.3      3473
5.6      3168
6.9      3128
3.8      3030
        ...
37.4        1
41.8        1
38.3        1
38.0        1
44.3        1
Name: count, Length: 182, dtype: int64
wind_kph
wind_kph
3.6     13724
6.8      3473
9.0      3168
11.2     3128
6.1      3030
        ...
60.1        1
67.3        1
61.6        1
61.2        1
71.3        1
Name: count, Length: 182, dtype: int64
wind_degree
wind_degree
10     1346
90      942
100     848
80      818
110     748
       ...
321     224
291     222
286     216
274     215
271     215
Name: count, Length: 360, dtype: int64
wind_direction
wind_direction
E      11552
ENE    10064
ESE     8537
N       8057
NNE     7970
S       7504
WSW     7313
SSW     7300
SW      7289
SSE     7224
NE      7038
NNW     6994
SE      6608
W       6443
WNW     6411
NW      6272
Name: count, dtype: int64
pressure_mb
pressure_mb
1013.0    9566
1012.0    9352
1014.0    9128
1011.0    8446
1015.0    8075
          ...
3000.0       1
969.0        1
962.0        1
968.0        1
1053.0       1
Name: count, Length: 92, dtype: int64
pressure_in
pressure_in
29.91    7031
29.88    7028
29.94    6889
29.85    6123
29.97    6024
         ...
28.41       1
30.97       1
30.81       1
28.59       1
31.09       1
Name: count, Length: 212, dtype: int64
precip_mm
precip_mm
0.00     81459
0.01      6652
0.02      3475
0.03      2416
0.04      1859
         ...
11.41        1
7.06         1
4.80         1
4.64         1
9.05         1
Name: count, Length: 629, dtype: int64
precip_in
precip_in
0.00    103363
0.01      7738
0.02      3728
0.03      2232
0.04      1581
         ...
0.93         1
1.08         1
0.43         1
0.46         1
0.66         1
Name: count, Length: 74, dtype: int64
humidity
humidity
94     7101
100    5721
79     4743
89     4342
84     3865
       ...
6       145
5       135
4        47
3         7
2         2
Name: count, Length: 99, dtype: int64
cloud
cloud
0      31338
75     21631
25     17371
50     14561
100     8876
       ...
95        73
98        71
91        70
96        70
97        66
Name: count, Length: 101, dtype: int64
feels_like_celsius
feels_like_celsius
 24.6    1583
 24.7    1171
 25.1     913
 25.0     875
 25.2     849
         ...
-33.6       1
-36.7       1
-29.3       1
-34.3       1
-33.0       1
Name: count, Length: 816, dtype: int64
feels_like_fahrenheit
feels_like_fahrenheit
 76.2    846
 76.4    837
 76.3    824
 70.0    757
 70.3    723
        ...
-2.4       1
-18.6      1
-29.2      1
-26.1      1
 6.7       1
Name: count, Length: 1414, dtype: int64
visibility_km
visibility_km
10.0    96719
9.0      5003
8.0      4411
7.0      2669
6.0      2303
        ...
3.3        16
18.0        7
9.5         2
5.5         1
6.5         1
Name: count, Length: 71, dtype: int64
visibility_miles
visibility_miles
6.0     96872
4.0      7081
5.0      5005
3.0      4581
1.0      2558
0.0      1762
2.0      1761
14.0     1555
9.0       789
13.0      219
8.0       196
11.0      180
19.0       17
Name: count, dtype: int64
uv_index
uv_index
0.0     28312
1.0      6572
6.0      6260
7.0      5640
8.0      4124
        ...
15.5        8
16.0        7
15.9        7
16.1        1
16.3        1
Name: count, Length: 163, dtype: int64
gust_mph
gust_mph
6.7     7352
7.0     1583
7.5     1415
4.9     1343
8.5     1321
        ...
47.0       1
49.8       1
51.4       1
44.8       1
55.4       1
Name: count, Length: 508, dtype: int64
gust_kph
gust_kph
10.8     7234
9.1      1332
8.3      1200
12.9     1192
16.2     1142
         ...
70.0        1
73.9        1
73.2        1
105.4       1
89.2        1
Name: count, Length: 775, dtype: int64
air_quality_Carbon_Monoxide
air_quality_Carbon_Monoxide
217.000      523
307.100      520
220.300      504
223.600      469
299.700      465
            ...
2876.750       1
11608.800      1
3322.600       1
103.789        1
178.678        1
Name: count, Length: 6034, dtype: int64
air_quality_Ozone
air_quality_Ozone
51.0     1752
52.0     1751
53.0     1749
48.0     1733
56.0     1720
         ...
234.0       1
220.0       1
279.0       1
188.0       1
198.0       1
Name: count, Length: 635, dtype: int64
air_quality_Nitrogen_dioxide
air_quality_Nitrogen_dioxide
0.000     2725
0.185     1764
0.740     1621
0.370     1592
1.850     1567
          ...
69.150       1
65.950       1
68.150       1
18.626       1
26.626       1
Name: count, Length: 2765, dtype: int64
air_quality_Sulphur_dioxide
air_quality_Sulphur_dioxide
0.555      3202
0.185      3143
0.370      3113
0.925      2806
0.740      2784
           ...
157.350       1
66.350        1
87.950        1
194.150       1
73.250        1
Name: count, Length: 2716, dtype: int64
air_quality_PM2.5
air_quality_PM2.5
0.500     1011
9.250      625
7.400      559
11.100     559
9.065      526
          ...
6.326        1
37.026       1
65.650       1
12.789       1
32.726       1
Name: count, Length: 4961, dtype: int64
air_quality_PM10
air_quality_PM10
12.950      439
9.250       410
15.540      405
18.500      386
16.835      374
           ...
21.905        1
10.995        1
1010.450      1
277.450       1
2928.950      1
Name: count, Length: 7121, dtype: int64
air_quality_us-epa-index
air_quality_us-epa-index
1    64954
2    38672
3    10116
4     7262
5     1134
6      438
Name: count, dtype: int64
air_quality_gb-defra-index
air_quality_gb-defra-index
1     52511
2     32816
3     15072
10     7603
4      4249
5      3277
6      2563
8      1621
7      1545
9      1319
Name: count, dtype: int64
sunrise
sunrise
05:57 AM    1297
05:56 AM    1295
05:55 AM    1283
05:54 AM    1256
06:17 AM    1227
            ...
10:37 AM       1
10:31 AM       1
09:59 AM       1
09:56 AM       1
09:53 AM       1
Name: count, Length: 492, dtype: int64
sunset
sunset
06:02 PM    1220
06:03 PM    1133
06:28 PM    1083
06:21 PM    1027
06:04 PM    1026
            ...
11:11 PM       1
11:16 PM       1
11:13 PM       1
03:00 PM       1
03:03 PM       1
Name: count, Length: 547, dtype: int64
moonrise
moonrise
No moonrise    4084
12:00 AM        242
01:05 PM        124
11:45 AM        112
06:15 PM        111
               ...
02:55 AM         57
09:20 PM         56
10:16 PM         55
08:39 AM         53
06:29 AM         49
Name: count, Length: 1441, dtype: int64
moonset
moonset
No moonset    4081
12:00 AM       251
12:01 AM       116
01:08 AM       114
01:55 AM       114
              ...
07:15 PM        58
09:24 PM        56
04:41 AM        55
06:32 AM        51
06:33 AM        50
Name: count, Length: 1441, dtype: int64
moon_phase
moon_phase
Waxing Gibbous     26931
Waxing Crescent    26701
Waning Crescent    26010
Waning Gibbous     25561
Full Moon           4517
Last Quarter        4305
New Moon            4282
First Quarter       4269
Name: count, dtype: int64
moon_illumination
moon_illumination
100    4969
0      4961
1      4271
99     3972
2      2697
       ...
66      531
61      482
62      475
39      464
36      450
Name: count, Length: 101, dtype: int64