In [2]:
import pandas as pd
import numpy as np

In [ ]:
file_path = r"data\processed\global_weather_cleaned_daily.csv"

df = pd.read_csv(
    file_path,
    parse_dates=["last_updated"]
)

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (123356, 34)

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,condition_text,wind_kph,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15:00,26.6,Partly Cloudy,13.3,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45:00,19.0,Partly cloudy,11.2,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45:00,23.0,Sunny,15.1,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45:00,6.3,Light drizzle,11.9,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45:00,26.0,Partly cloudy,13.0,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

In [4]:
df.dtypes

country                                    str
location_name                              str
latitude                               float64
longitude                              float64
timezone                                   str
last_updated_epoch                       int64
last_updated                    datetime64[us]
temperature_celsius                    float64
condition_text                             str
wind_kph                               float64
wind_degree                              int64
wind_direction                             str
pressure_mb                              int64
precip_mm                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
visibility_km                          float64
uv_index                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                                    str
sunset                                     str
moonrise                                   str
moonset                                    str
moon_phase                                 str
moon_illumination                        int64
dtype: object

In [5]:
df = df[df['wind_kph'] < 200]
df = df[(df['pressure_mb'] > 900) & (df['pressure_mb'] < 1100)]
df.replace(-9999, np.nan, inplace=True)
print("Final Dataset Shape:", df.shape)

Final Dataset Shape: (123350, 34)

In [6]:
df.describe()

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,123350.000000,123350.000000,1.233500e+05,123350,123350.000000,123350.000000,123350.000000,123350.000000,123350.00000,123350.000000,...,123350.000000,123349.000000,123350.000000,123350.000000,123349.000000,123350.000000,123350.000000,123350.000000,123350.000000,123350.000000
mean,19.192138,21.995788,1.743298e+09,2025-03-30 03:39:42.420754,21.665510,12.966261,169.266405,1014.053085,0.13706,66.061532,...,18.276794,478.760364,59.073664,15.295230,10.802469,24.657200,49.297213,1.712006,2.638589,49.997236
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-29.800000,3.600000,1.000000,947.000000,0.00000,2.000000,...,3.600000,57.850000,0.000000,0.000000,0.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729588e+09,2024-10-22 15:03:45,16.300000,6.500000,80.000000,1010.000000,0.00000,50.000000,...,10.400000,212.750000,39.000000,1.613000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.240000,1.743327e+09,2025-03-30 11:30:00,24.100000,11.200000,162.000000,1014.000000,0.00000,71.000000,...,15.500000,304.850000,56.000000,5.450000,2.450000,14.300000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756973e+09,2025-09-04 12:00:00,28.100000,17.600000,256.000000,1018.000000,0.03000,85.000000,...,24.300000,474.850000,75.000000,17.760000,8.695000,28.250000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770710e+09,2026-02-10 21:00:00,49.200000,172.100000,360.000000,1080.000000,42.24000,100.000000,...,179.300000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000
std,24.427437,65.792696,1.583386e+07,NaN,9.547589,8.337903,103.421349,6.986957,0.57280,24.029276,...,11.168625,785.321634,31.193200,24.364625,23.830879,37.971509,151.973315,0.951666,2.475319,35.024420

In [ ]:
weather_cols = [
    'temperature_celsius',
    'humidity',
    'wind_kph',
    'precip_mm',
    'pressure_mb',
    'uv_index'
]
df[weather_cols].describe()

,temperature_celsius,humidity,wind_kph,precip_mm,pressure_mb,uv_index
count,123350.000000,123350.000000,123350.000000,123350.00000,123350.000000,123350.000000
mean,21.665510,66.061532,12.966261,0.13706,1014.053085,3.462472
std,9.547589,24.029276,8.337903,0.57280,6.986957,3.568053
min,-29.800000,2.000000,3.600000,0.00000,947.000000,0.000000
25%,16.300000,50.000000,6.500000,0.00000,1010.000000,0.100000
50%,24.100000,71.000000,11.200000,0.00000,1014.000000,2.200000
75%,28.100000,85.000000,17.600000,0.03000,1018.000000,6.000000
max,49.200000,100.000000,172.100000,42.24000,1080.000000,16.300000

In [8]:
df[weather_cols].quantile([0.25, 0.5, 0.75, 0.95, 0.99])

,temperature_celsius,humidity,wind_kph,precip_mm,pressure_mb,uv_index
0.25,16.3,50.0,6.5,0.00,1010.0,0.1
0.50,24.1,71.0,11.2,0.00,1014.0,2.2
0.75,28.1,85.0,17.6,0.03,1018.0,6.0
0.95,34.1,99.0,29.2,0.80,1026.0,10.2
0.99,40.0,100.0,37.4,2.15,1032.0,13.1

In [9]:
corr_matrix = df[weather_cols].corr()
corr_matrix

,temperature_celsius,humidity,wind_kph,precip_mm,pressure_mb,uv_index
temperature_celsius,1.000000,-0.345056,0.123278,0.029174,-0.432094,0.487524
humidity,-0.345056,1.000000,-0.100817,0.175268,-0.005010,-0.557747
wind_kph,0.123278,-0.100817,1.000000,0.009585,-0.177936,0.072470
precip_mm,0.029174,0.175268,0.009585,1.000000,-0.124881,-0.066224
pressure_mb,-0.432094,-0.005010,-0.177936,-0.124881,1.000000,-0.077703
uv_index,0.487524,-0.557747,0.072470,-0.066224,-0.077703,1.000000

In [19]:
df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month

monthly_avg = df.groupby(['year', 'month']).agg({
    'temperature_celsius': 'mean',
    'precip_mm': 'mean',
    'wind_kph': 'mean',
    'humidity': 'mean'
}).reset_index()

monthly_avg

    year  month  temperature_celsius  precip_mm   wind_kph   humidity
0   2024      5            25.151744   0.160397  14.248529  59.806491
1   2024      6            26.456633   0.156761  14.108873  58.788249
2   2024      7            26.800448   0.163338  13.979538  59.406200
3   2024      8            26.789677   0.166756  13.915649  59.690984
4   2024      9            25.124402   0.167121  13.235980  63.318135
5   2024     10            22.335382   0.125759  12.237375  66.678904
6   2024     11            19.424566   0.135756  12.148272  67.930376
7   2024     12            17.751894   0.111050  13.065691  65.780811
8   2025      1            17.392440   0.125386  13.005262  67.125562
9   2025      2            17.427493   0.110126  13.334696  66.105205
10  2025      3            20.095299   0.131084  13.267721  64.144347
11  2025      4            21.965060   0.129513  13.304376  63.027350
12  2025      5            23.307798   0.147239  13.325071  63.686909
13  2025      6            24.958108   0.122881  13.767311  62.981697
14  2025      7            25.298030   0.170793  13.448825  65.011420
15  2025      8            24.706056   0.140477  12.650480  66.195235
16  2025      9            23.371917   0.138811  12.325398  69.124337
17  2025     10            20.872270   0.131231  11.935159  71.041198
18  2025     11            18.367749   0.136790  11.480841  72.552042
19  2025     12            16.252225   0.111309  11.921621  75.401985
20  2026      1            14.713650   0.119406  12.506765  73.644973
21  2026      2            15.475411   0.095534  12.188142  74.017454

In [11]:
yearly_avg = df.groupby('year').agg({
    'temperature_celsius': 'mean',
    'precip_mm': 'mean',
    'wind_kph': 'mean'
}).reset_index()

yearly_avg

   year  temperature_celsius  precip_mm   wind_kph
0  2024            23.611535   0.147420  13.310080
1  2025            21.188987   0.133169  12.810291
2  2026            14.904212   0.113434  12.427058

In [21]:
country_avg = df.groupby('country').agg({
    'temperature_celsius': 'mean',
    'precip_mm': 'mean',
    'wind_kph': 'mean',
    'humidity': 'mean'
}).reset_index()

country_avg.head()

       country  temperature_celsius  precip_mm   wind_kph   humidity
0  Afghanistan            19.502208   0.036435   8.746372  25.362776
1      Albania            20.350789   0.142681   8.944953  55.429022
2      Algeria            21.348657   0.046445  13.104265  62.296998
3      Andorra             9.902524   0.125158   8.285647  62.801262
4       Angola            26.125710   0.027744   9.380599  74.138801

In [13]:

top10_hot = country_avg.sort_values(
    by='temperature_celsius',
    ascending=False
).head(10)

top10_hot

,country,temperature_celsius,precip_mm,wind_kph,humidity
158,Saudi Arabien,45.000000,0.000000,24.500000,7.000000
114,Marrocos,40.300000,0.000000,16.900000,14.000000
189,Turkménistan,37.800000,0.000000,22.000000,11.000000
208,Турция,34.000000,0.000000,24.100000,44.000000
147,Qatar,32.843760,0.000490,18.528752,40.126382
194,United Arab Emirates,32.838013,0.000268,15.687066,42.933754
94,Kuwait,31.839590,0.004858,17.217666,26.413249
48,Djibouti,31.832595,0.025570,16.846044,54.147152
136,Oman,31.630599,0.001104,15.010410,52.113565
157,Saudi Arabia,31.500316,0.001677,15.292089,17.148734

In [14]:
top10_rain = country_avg.sort_values(
    by='precip_mm',
    ascending=False
).head(10)

top10_rain

,country,temperature_celsius,precip_mm,wind_kph,humidity
96,Lao People's Democratic Republic,25.000000,1.970000,9.000000,95.000000
100,Letonia,20.600000,1.830000,13.300000,94.000000
113,Malásia,24.300000,1.550000,6.500000,93.000000
109,Malaysia,30.116877,0.585615,6.441640,70.580442
191,USA United States of America,24.533333,0.530000,12.933333,66.000000
24,Brunei Darussalam,29.224487,0.520269,9.051975,77.639810
162,Sierra Leone,26.035658,0.516830,8.857369,81.291601
140,Papua New Guinea,26.757346,0.502085,14.543444,83.503949
128,Nepal,22.912500,0.490839,6.978639,59.337025
79,Indonesia,28.088101,0.487415,10.808195,74.884161

In [15]:
temp_threshold = df['temperature_celsius'].quantile(0.95)
rain_threshold = df['precip_mm'].quantile(0.95)
wind_threshold = df['wind_kph'].quantile(0.95)

In [16]:

extreme_heat = df[df['temperature_celsius'] > temp_threshold]
extreme_rain = df[df['precip_mm'] > rain_threshold]
extreme_wind = df[df['wind_kph'] > wind_threshold]

In [17]:
print("Extreme Heat Events:", extreme_heat.shape[0])
print("Extreme Rain Events:", extreme_rain.shape[0])
print("Extreme Wind Events:", extreme_wind.shape[0])

Extreme Heat Events: 5908
Extreme Rain Events: 6152
Extreme Wind Events: 6058

In [18]:
global_summary = pd.DataFrame({
    "Metric": [
        "Average Temperature",
        "Average Rainfall",
        "Average Wind Speed",
        "Average Humidity"
    ],
    "Value": [
        df['temperature_celsius'].mean(),
        df['precip_mm'].mean(),
        df['wind_kph'].mean(),
        df['humidity'].mean()
    ]
})

global_summary

                Metric      Value
0  Average Temperature  21.665510
1     Average Rainfall   0.137060
2   Average Wind Speed  12.966261
3     Average Humidity  66.061532

1️⃣ Statistical Analysis of Weather Variables

To understand the overall behavior of global weather patterns, descriptive statistical analysis was performed on key meteorological variables including temperature, humidity, precipitation, wind speed, pressure, and UV index.

🔹 Distribution Analysis

The dataset consists of over 120,000 weather observations across multiple global locations. Statistical summaries revealed:

Temperature values range from extreme cold conditions (below freezing) to very high temperatures typical of tropical and desert climates.

Precipitation distribution is highly right-skewed, indicating that most days experience little to no rainfall, while a small percentage of days experience heavy rainfall events.

Wind speed values are mostly concentrated in moderate ranges, with few extreme wind events.

Humidity levels show broad variation depending on geographic location and climate type.

This distribution analysis helps establish the variability and global diversity of climate conditions.

2️⃣ Correlation Analysis

A correlation matrix was computed to examine relationships between major weather variables.

🔹 Key Observations:

Humidity and Precipitation show a positive correlation, indicating that higher humidity levels are often associated with rainfall events.

Temperature and Humidity demonstrate mild inverse relationships in certain regions, reflecting dry heat conditions in arid climates.

Wind speed and precipitation show weak to moderate relationships, suggesting wind contributes to storm systems but is not always directly proportional to rainfall.

Pressure tends to vary inversely during extreme weather events, particularly during storms.

Correlation analysis helps identify interactions between atmospheric variables and supports climate behavior understanding.

3️⃣ Seasonal Patterns & Time-Series Trends

To analyze climate behavior over time, monthly and yearly aggregations were performed.

🔹 Monthly Trends

Monthly averages revealed clear seasonal cycles:

Temperature peaks during mid-year months in many regions, indicating summer season effects.

Cooler temperatures are observed during early and late months of the year.

Rainfall patterns vary significantly by region, with some countries experiencing monsoon-driven seasonal spikes.

Wind speed shows mild seasonal fluctuation but remains relatively stable compared to precipitation.

These seasonal variations confirm predictable climate cycles and demonstrate temporal trends in global weather patterns.

4️⃣ Regional Comparison Across Countries

Country-wise aggregation was performed to compare average weather conditions across regions.

🔹 Regional Insights:

Tropical and desert regions show consistently higher average temperatures.

Coastal and equatorial countries display higher humidity levels.

Certain regions experience significantly higher rainfall due to monsoon systems or tropical storm activity.

Wind intensity varies across geographical terrain, with some regions showing elevated wind averages.

Top 10 hottest and rainiest countries were identified to highlight climatic extremes across regions.

This comparative analysis helps visualize how climate differs globally.

5️⃣ Identification of Extreme Weather Events

Extreme weather events were identified using the 95th percentile threshold for temperature, precipitation, and wind speed.

🔹 Extreme Heat Events:

Days with temperatures above the 95th percentile were classified as extreme heat days. These are concentrated primarily in warmer climate zones.

🔹 Extreme Rainfall Events:

Precipitation values above the 95th percentile indicate heavy rainfall events. These are generally localized but intense.

🔹 Extreme Wind Events:

Wind speeds above the upper threshold represent potential storm or severe weather conditions.

This percentile-based approach ensures objective and statistically grounded identification of anomalies.