In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
raw_path = "data/raw/GlobalWeatherRepository.csv"

df = pd.read_csv(raw_path, engine="python")

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,16-05-2024 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,4:50 AM,6:50 PM,12:12 PM,1:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,16-05-2024 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,5:21 AM,7:54 PM,12:58 PM,2:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,16-05-2024 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,5:40 AM,7:50 PM,1:15 PM,2:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,16-05-2024 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,6:31 AM,9:11 PM,2:12 PM,3:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,16-05-2024 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,6:12 AM,5:55 PM,1:17 PM,12:38 AM,Waxing Gibbous,55

In [3]:
df.shape

(123356, 41)

In [4]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='str')

In [5]:
df.dtypes

country                             str
location_name                       str
latitude                        float64
longitude                       float64
timezone                            str
last_updated_epoch                int64
last_updated                        str
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                      str
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                      str
pressure_mb                       int64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                  int64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                             str
sunset                              str
moonrise                            str
moonset                             str
moon_phase                          str
moon_illumination                 int64
dtype: object

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123356 entries, 0 to 123355
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       123356 non-null  str
 1   location_name                 123356 non-null  str
 2   latitude                      123356 non-null  float64
 3   longitude                     123356 non-null  float64
 4   timezone                      123356 non-null  str
 5   last_updated_epoch            123356 non-null  int64
 6   last_updated                  123356 non-null  str
 7   temperature_celsius           123356 non-null  float64
 8   temperature_fahrenheit        123356 non-null  float64
 9   condition_text                123356 non-null  str
 10  wind_mph                      123356 non-null  float64
 11  wind_kph                      123356 non-null  float64
 12  wind_degree                   123356 non-null  int64
 13  wind_direction                123356 non-null  str
 14  pressure_mb                   123356 non-null  int64
 15  pressure_in                   123356 non-null  float64
 16  precip_mm                     123356 non-null  float64
 17  precip_in                     123356 non-null  float64
 18  humidity                      123356 non-null  int64
 19  cloud                         123356 non-null  int64
 20  feels_like_celsius            123356 non-null  float64
 21  feels_like_fahrenheit         123356 non-null  float64
 22  visibility_km                 123356 non-null  float64
 23  visibility_miles              123356 non-null  int64
 24  uv_index                      123356 non-null  float64
 25  gust_mph                      123356 non-null  float64
 26  gust_kph                      123356 non-null  float64
 27  air_quality_Carbon_Monoxide   123356 non-null  float64
 28  air_quality_Ozone             123356 non-null  float64
 29  air_quality_Nitrogen_dioxide  123356 non-null  float64
 30  air_quality_Sulphur_dioxide   123356 non-null  float64
 31  air_quality_PM2.5             123356 non-null  float64
 32  air_quality_PM10              123356 non-null  float64
 33  air_quality_us-epa-index      123356 non-null  int64
 34  air_quality_gb-defra-index    123356 non-null  int64
 35  sunrise                       123356 non-null  str
 36  sunset                        123356 non-null  str
 37  moonrise                      123356 non-null  str
 38  moonset                       123356 non-null  str
 39  moon_phase                    123356 non-null  str
 40  moon_illumination             123356 non-null  int64
dtypes: float64(21), int64(9), str(11)
memory usage: 50.6 MB

In [7]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df["last_updated"] = pd.to_datetime(
    df["last_updated"],
    format="%d-%m-%Y %H:%M",
    errors="coerce"
)

In [10]:
df["last_updated"].head()

0   2024-05-16 13:15:00
1   2024-05-16 10:45:00
2   2024-05-16 09:45:00
3   2024-05-16 10:45:00
4   2024-05-16 09:45:00
Name: last_updated, dtype: datetime64[us]

In [11]:
df.describe()

,latitude,longitude,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,123356.000000,123356.000000,1.233560e+05,123356,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,...,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000
mean,19.191767,21.994709,1.743297e+09,2025-03-30 03:25:01.515127,21.665486,70.999629,8.072977,12.995777,169.263870,1014.085428,...,18.306360,478.688774,59.073220,15.295481,10.721284,24.656709,49.296385,1.711996,2.638558,49.998354
min,-41.300000,-175.200000,1.715849e+09,2024-05-16 01:45:00,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729588e+09,2024-10-22 14:37:30,16.300000,61.300000,4.000000,6.500000,80.000000,1010.000000,...,10.400000,212.750000,39.000000,1.613000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.278350,1.743327e+09,2025-03-30 11:30:00,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,...,15.500000,304.850000,56.000000,5.450000,2.450000,14.300000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756973e+09,2025-09-04 12:00:00,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,...,24.300000,474.850000,75.000000,17.760000,8.695000,28.250000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770710e+09,2026-02-10 21:00:00,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000
std,24.427080,65.792350,1.583412e+07,NaN,9.547590,17.185514,7.391056,11.891706,103.421709,10.627979,...,14.026397,785.903701,31.192635,24.365959,37.150392,37.970841,151.969915,0.951659,2.475295,35.024758

In [12]:
df["temperature_celsius"].min(), df["temperature_celsius"].max()

(np.float64(-29.8), np.float64(49.2))

In [13]:
columns_to_drop = [
    "temperature_fahrenheit",
    "feels_like_fahrenheit",
    "wind_mph",
    "pressure_in",
    "precip_in",
    "visibility_miles",
    "gust_mph"
]

df.drop(columns=columns_to_drop, inplace=True, errors="ignore")

In [14]:
os.makedirs("data/processed", exist_ok=True)
df.to_csv(
    "data/processed/global_weather_cleaned_daily.csv",
    index=False
)

In [15]:
df["year_month"] = df["last_updated"].dt.to_period("M")

monthly_avg = (
    df.groupby("year_month")
    .mean(numeric_only=True)
    .reset_index()
)

monthly_avg.head()

,year_month,latitude,longitude,last_updated_epoch,temperature_celsius,wind_kph,wind_degree,pressure_mb,precip_mm,humidity,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
0,2024-05,19.330079,21.252653,1.716476e+09,25.153214,14.322680,170.234384,1013.072468,0.160403,59.805033,...,22.285567,527.585263,60.698423,10.185324,6.788720,17.821771,33.466252,1.391146,1.850819,78.780776
1,2024-06,19.169585,21.786945,1.718494e+09,26.456036,14.694197,178.421044,1011.961081,0.156849,58.788014,...,22.217324,501.149371,63.579353,9.038798,6.582004,16.837369,30.644171,1.358016,1.788359,49.536077
2,2024-07,19.090607,22.195843,1.721096e+09,26.800448,13.979538,183.502419,1011.521233,0.163338,59.406200,...,20.857391,446.389697,65.601846,8.044042,4.098208,15.947017,28.087225,1.318043,1.712955,43.570865
3,2024-08,19.107315,22.088584,1.723808e+09,26.789677,13.915649,180.594045,1011.993052,0.166756,59.690984,...,20.407428,438.953069,67.023672,8.006352,5.857237,14.332291,24.084119,1.310835,1.720430,45.561125
4,2024-09,19.064397,22.147510,1.726441e+09,25.124402,13.235980,169.814720,1013.014173,0.167121,63.318135,...,18.974658,407.732131,70.947643,10.442420,9.618837,20.946278,44.547416,1.618852,2.353654,46.063525

In [16]:
monthly_avg.to_csv(
    "data/processed/global_weather_cleaned_monthly.csv",
    index=False
)

In [17]:
df.dtypes

country                                    str
location_name                              str
latitude                               float64
longitude                              float64
timezone                                   str
last_updated_epoch                       int64
last_updated                    datetime64[us]
temperature_celsius                    float64
condition_text                             str
wind_kph                               float64
wind_degree                              int64
wind_direction                             str
pressure_mb                              int64
precip_mm                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
visibility_km                          float64
uv_index                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                                    str
sunset                                     str
moonrise                                   str
moonset                                    str
moon_phase                                 str
moon_illumination                        int64
year_month                           period[M]
dtype: object