In [6]:
from google.colab import files
uploaded = files.upload()

Saving GlobalWeatherRepository.csv to GlobalWeatherRepository.csv

In [15]:

import pandas as pd
import numpy as np

# load
df = pd.read_csv("GlobalWeatherRepository.csv")

df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [17]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123356 entries, 0 to 123355
Data columns (total 41 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       123356 non-null  object
 1   location_name                 123356 non-null  object
 2   latitude                      123356 non-null  float64
 3   longitude                     123356 non-null  float64
 4   timezone                      123356 non-null  object
 5   last_updated_epoch            123356 non-null  int64
 6   last_updated                  123356 non-null  object
 7   temperature_celsius           123356 non-null  float64
 8   temperature_fahrenheit        123356 non-null  float64
 9   condition_text                123356 non-null  object
 10  wind_mph                      123356 non-null  float64
 11  wind_kph                      123356 non-null  float64
 12  wind_degree                   123356 non-null  int64
 13  wind_direction                123356 non-null  object
 14  pressure_mb                   123356 non-null  float64
 15  pressure_in                   123356 non-null  float64
 16  precip_mm                     123356 non-null  float64
 17  precip_in                     123356 non-null  float64
 18  humidity                      123356 non-null  int64
 19  cloud                         123356 non-null  int64
 20  feels_like_celsius            123356 non-null  float64
 21  feels_like_fahrenheit         123356 non-null  float64
 22  visibility_km                 123356 non-null  float64
 23  visibility_miles              123356 non-null  float64
 24  uv_index                      123356 non-null  float64
 25  gust_mph                      123356 non-null  float64
 26  gust_kph                      123356 non-null  float64
 27  air_quality_Carbon_Monoxide   123356 non-null  float64
 28  air_quality_Ozone             123356 non-null  float64
 29  air_quality_Nitrogen_dioxide  123356 non-null  float64
 30  air_quality_Sulphur_dioxide   123356 non-null  float64
 31  air_quality_PM2.5             123356 non-null  float64
 32  air_quality_PM10              123356 non-null  float64
 33  air_quality_us-epa-index      123356 non-null  int64
 34  air_quality_gb-defra-index    123356 non-null  int64
 35  sunrise                       123356 non-null  object
 36  sunset                        123356 non-null  object
 37  moonrise                      123356 non-null  object
 38  moonset                       123356 non-null  object
 39  moon_phase                    123356 non-null  object
 40  moon_illumination             123356 non-null  int64
dtypes: float64(23), int64(7), object(11)
memory usage: 38.6+ MB

In [19]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,123356.000000,123356.000000,1.233560e+05,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,...,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000,123356.000000
mean,19.191767,21.994709,1.743297e+09,21.665486,70.999629,8.072977,12.995777,169.263870,1014.085428,29.945288,...,18.306360,478.688774,59.073220,15.295481,10.721284,24.656709,49.296385,1.711996,2.638558,49.998354
std,24.427080,65.792350,1.583412e+07,9.547590,17.185514,7.391056,11.891706,103.421709,10.627979,0.313805,...,14.026397,785.903701,31.192635,24.365959,37.150392,37.970841,151.969915,0.951659,2.475295,35.024758
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729588e+09,16.300000,61.300000,4.000000,6.500000,80.000000,1010.000000,29.830000,...,10.400000,212.750000,39.000000,1.613000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.278350,1.743327e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,...,15.500000,304.850000,56.000000,5.450000,2.450000,14.300000,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756973e+09,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.300000,474.850000,75.000000,17.760000,8.695000,28.250000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770710e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [22]:
print("Missing values before:\n", df.isnull().sum())

# clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")


df = df.drop_duplicates()

# fill nulls
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include="object").columns

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("\nMissing values after:\n", df.isnull().sum())

# save
df.to_csv("preprocessed_weather_dataset.csv", index=False)


files.download("preprocessed_weather_dataset.csv")

Missing values before:
 country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_carbon_monoxide     0
air_quality_ozone               0
air_quality_nitrogen_dioxide    0
air_quality_sulphur_dioxide     0
air_quality_pm2.5               0
air_quality_pm10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

Missing values after:
 country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_carbon_monoxide     0
air_quality_ozone               0
air_quality_nitrogen_dioxide    0
air_quality_sulphur_dioxide     0
air_quality_pm2.5               0
air_quality_pm10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64