# ClimateScope – Dataset Overview

This notebook provides an overview and understanding of the dataset used in the ClimateScope project.
The goal is to familiarize with the structure, attributes, and characteristics of the data
before performing any preprocessing or analysis.

In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
df = pd.read_csv("../data/raw/GlobalWeatherRepository.csv")
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [4]:
df.shape

(122966, 41)

In [18]:
(df.columns)

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [12]:
df.dtypes

country                          object
location_name                    object
latitude                        float64
longitude                       float64
timezone                         object
last_updated_epoch                int64
last_updated                     object
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                   object
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                   object
pressure_mb                     float64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                float64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                          object
sunset                           object
moonrise                         object
moonset                          object
moon_phase                       object
moon_illumination                 int64
dtype: object

In [13]:
df.info

<bound method DataFrame.info of             country     location_name  latitude  longitude         timezone  \
0       Afghanistan             Kabul   34.5200    69.1800       Asia/Kabul
1           Albania            Tirana   41.3300    19.8200    Europe/Tirane
2           Algeria           Algiers   36.7600     3.0500   Africa/Algiers
3           Andorra  Andorra La Vella   42.5000     1.5200   Europe/Andorra
4            Angola            Luanda   -8.8400    13.2300    Africa/Luanda
...             ...               ...       ...        ...              ...
122961    Venezuela           Caracas   10.5000   -66.9167  America/Caracas
122962      Vietnam             Hanoi   21.0333   105.8500     Asia/Bangkok
122963        Yemen             Sanaa   15.3547    44.2067        Asia/Aden
122964       Zambia            Lusaka  -15.4167    28.2833    Africa/Lusaka
122965     Zimbabwe            Harare  -17.8178    31.0447    Africa/Harare

        last_updated_epoch      last_updated  temperature_celsius  \
0               1715849100  2024-05-16 13:15                 26.6
1               1715849100  2024-05-16 10:45                 19.0
2               1715849100  2024-05-16 09:45                 23.0
3               1715849100  2024-05-16 10:45                  6.3
4               1715849100  2024-05-16 09:45                 26.0
...                    ...               ...                  ...
122961          1770533100  2026-02-08 02:45                 15.8
122962          1770533100  2026-02-08 13:45                 14.3
122963          1770533100  2026-02-08 09:45                 15.4
122964          1770533100  2026-02-08 08:45                 18.5
122965          1770533100  2026-02-08 08:45                 19.3

        temperature_fahrenheit     condition_text  wind_mph  wind_kph  \
0                         79.8      Partly Cloudy       8.3      13.3
1                         66.2      Partly cloudy       6.9      11.2
2                         73.4              Sunny       9.4      15.1
3                         43.3      Light drizzle       7.4      11.9
4                         78.8      Partly cloudy       8.1      13.0
...                        ...                ...       ...       ...
122961                    60.4      Partly Cloudy       2.2       3.6
122962                    57.7           Overcast      13.9      22.3
122963                    59.8              Sunny       2.5       4.0
122964                    65.3  Light rain shower       4.3       6.8
122965                    66.7      Partly Cloudy       6.5      10.4

        wind_degree wind_direction  pressure_mb  pressure_in  precip_mm  \
0               338            NNW       1012.0        29.89       0.00
1               320             NW       1012.0        29.88       0.10
2               280              W       1011.0        29.85       0.00
3               215             SW       1007.0        29.75       0.30
4               150            SSE       1011.0        29.85       0.00
...             ...            ...          ...          ...        ...
122961          155            SSE       1016.0        30.01       0.00
122962           20            NNE       1023.0        30.21       0.12
122963          101              E       1020.0        30.13       0.00
122964           25            NNE       1016.0        29.99       0.16
122965           22            NNE       1017.0        30.03       0.00

        precip_in  humidity  cloud  feels_like_celsius  feels_like_fahrenheit  \
0            0.00        24     30                25.3                   77.5
1            0.00        94     75                19.0                   66.2
2            0.00        29      0                24.6                   76.4
3            0.01        61    100                 3.8                   38.9
4            0.00        89     50                28.7                   83.6
...           ...       ...    ...                 ...                    ...
122961       0.00        87     29                15.8                   60.4
122962       0.00        88    100                12.6                   54.8
122963       0.00        30      0                15.4                   59.8
122964       0.01        96     72                18.5                   65.2
122965       0.00        79     30                19.3                   66.7

        visibility_km  visibility_miles  uv_index  gust_mph  gust_kph  \
0                10.0               6.0       7.0       9.5      15.3
1                10.0               6.0       5.0      11.4      18.4
2                10.0               6.0       5.0      13.9      22.3
3                 2.0               1.0       2.0       8.5      13.7
4                10.0               6.0       8.0      12.5      20.2
...               ...               ...       ...       ...       ...
122961           10.0               6.0       0.0       6.7      10.8
122962           10.0               6.0       0.4      18.2      29.3
122963           10.0               6.0       4.5       2.8       4.6
122964           10.0               6.0       1.5       7.2      11.6
122965           10.0               6.0       3.7       7.5      12.0

        air_quality_Carbon_Monoxide  air_quality_Ozone  \
0                            277.00              103.0
1                            193.60               97.3
2                            540.70               12.2
3                            170.20               64.4
4                           2964.00               19.0
...                             ...                ...
122961                       708.85               41.0
122962                       731.85               44.0
122963                       160.85               38.0
122964                       236.85               34.0
122965                       163.85               44.0

        air_quality_Nitrogen_dioxide  air_quality_Sulphur_dioxide  \
0                               1.10                         0.20
1                               0.90                         0.10
2                              65.10                        13.40
3                               1.60                         0.20
4                              72.70                        31.50
...                              ...                          ...
122961                          8.95                         2.05
122962                         10.45                        22.05
122963                          4.75                         1.55
122964                          5.65                         2.35
122965                          6.05                         1.75

        air_quality_PM2.5  air_quality_PM10  air_quality_us-epa-index  \
0                    8.40             26.60                         1
1                    1.10              2.00                         1
2                   10.40             18.40                         1
3                    0.70              0.90                         1
4                  183.40            262.30                         5
...                   ...               ...                       ...
122961              12.05             13.65                         1
122962              18.65             18.65                         2
122963              13.65             20.65                         1
122964               8.35              8.55                         1
122965              15.15             16.15                         1

        air_quality_gb-defra-index   sunrise    sunset     moonrise   moonset  \
0                                1  04:50 AM  06:50 PM     12:12 PM  01:11 AM
1                                1  05:21 AM  07:54 PM     12:58 PM  02:14 AM
2                                1  05:40 AM  07:50 PM     01:15 PM  02:14 AM
3                                1  06:31 AM  09:11 PM     02:12 PM  03:31 AM
4                               10  06:12 AM  05:55 PM     01:17 PM  12:38 AM
...                            ...       ...       ...          ...       ...
122961                           2  06:50 AM  06:34 PM  No moonrise  11:22 AM
122962                           2  06:31 AM  05:51 PM     11:41 PM  10:17 AM
122963                           2  06:30 AM  06:04 PM     11:47 PM  10:38 AM
122964                           1  06:00 AM  06:41 PM     11:04 PM  11:26 AM
122965                           2  05:47 AM  06:33 PM     10:49 PM  11:18 AM

            moon_phase  moon_illumination
0       Waxing Gibbous                 55
1       Waxing Gibbous                 55
2       Waxing Gibbous                 55
3       Waxing Gibbous                 55
4       Waxing Gibbous                 55
...                ...                ...
122961  Waning Gibbous                 63
122962  Waning Gibbous                 67
122963  Waning Gibbous                 66
122964  Waning Gibbous                 65
122965  Waning Gibbous                 65

[122966 rows x 41 columns]>

In [14]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,122966.000000,122966.000000,1.229660e+05,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000,122966.000000
mean,19.191466,21.995772,1.743211e+09,21.683350,71.031781,8.074984,12.999002,169.306320,1014.089008,29.945393,0.137210,0.005206,66.035050,40.013052,22.591329,72.658306,9.524734,5.627751,3.467825,11.374261,18.307045,479.170835,59.119896,15.302172,10.731101,24.671785,49.334233,1.712498,2.639884,49.995007
std,24.427584,65.792380,1.578390e+07,9.534753,17.162419,7.397698,11.902410,103.413261,10.639120,0.314134,0.573459,0.022665,24.031514,34.058867,11.394484,20.507660,2.663725,1.664072,3.568559,8.720943,14.034965,786.725561,31.202760,24.385287,37.197485,38.005182,152.130611,0.952091,2.476645,35.079076
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,0.000000,0.000000,2.000000,0.000000,-36.700000,-34.000000,0.000000,0.000000,0.000000,2.200000,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,3.750000,-6.836100,1.729588e+09,16.300000,61.300000,4.000000,6.500000,81.000000,1010.000000,29.830000,0.000000,0.000000,50.000000,0.000000,16.300000,61.300000,10.000000,6.000000,0.200000,6.400000,10.400000,212.750000,39.000000,1.610000,1.050000,7.150000,10.100000,1.000000,1.000000,15.000000
50%,17.250000,23.316700,1.743241e+09,24.100000,75.400000,6.900000,11.200000,162.000000,1014.000000,29.930000,0.000000,0.000000,71.000000,31.000000,25.400000,77.700000,10.000000,6.000000,2.200000,9.600000,15.500000,305.250000,56.000000,5.400000,2.450000,14.312500,20.350000,1.000000,2.000000,50.000000
75%,40.400000,50.580000,1.756886e+09,28.100000,82.600000,11.000000,17.600000,256.000000,1018.000000,30.060000,0.030000,0.000000,84.000000,75.000000,30.175000,86.300000,10.000000,6.000000,6.000000,15.100000,24.300000,475.450000,75.000000,17.760000,8.695000,28.250000,42.365000,2.000000,3.000000,85.000000
max,64.150000,179.220000,1.770533e+09,49.200000,120.600000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,42.240000,1.660000,100.000000,100.000000,51.200000,124.200000,32.000000,19.000000,16.300000,1845.700000,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [17]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64