In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("GlobalWeatherRepository.csv")

print(df.shape)
print(df.head())

(122381, 41)
       country     location_name  latitude  longitude        timezone  \
0  Afghanistan             Kabul     34.52      69.18      Asia/Kabul
1      Albania            Tirana     41.33      19.82   Europe/Tirane
2      Algeria           Algiers     36.76       3.05  Africa/Algiers
3      Andorra  Andorra La Vella     42.50       1.52  Europe/Andorra
4       Angola            Luanda     -8.84      13.23   Africa/Luanda

   last_updated_epoch      last_updated  temperature_celsius  \
0          1715849100  2024-05-16 13:15                 26.6
1          1715849100  2024-05-16 10:45                 19.0
2          1715849100  2024-05-16 09:45                 23.0
3          1715849100  2024-05-16 10:45                  6.3
4          1715849100  2024-05-16 09:45                 26.0

   temperature_fahrenheit condition_text  ...  air_quality_PM2.5  \
0                    79.8  Partly Cloudy  ...                8.4
1                    66.2  Partly cloudy  ...                1.1
2                    73.4          Sunny  ...               10.4
3                    43.3  Light drizzle  ...                0.7
4                    78.8  Partly cloudy  ...              183.4

   air_quality_PM10  air_quality_us-epa-index air_quality_gb-defra-index  \
0              26.6                         1                          1
1               2.0                         1                          1
2              18.4                         1                          1
3               0.9                         1                          1
4             262.3                         5                         10

    sunrise    sunset  moonrise   moonset      moon_phase  moon_illumination
0  04:50 AM  06:50 PM  12:12 PM  01:11 AM  Waxing Gibbous                 55
1  05:21 AM  07:54 PM  12:58 PM  02:14 AM  Waxing Gibbous                 55
2  05:40 AM  07:50 PM  01:15 PM  02:14 AM  Waxing Gibbous                 55
3  06:31 AM  09:11 PM  02:12 PM  03:31 AM  Waxing Gibbous                 55
4  06:12 AM  05:55 PM  01:17 PM  12:38 AM  Waxing Gibbous                 55

[5 rows x 41 columns]

In [9]:
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122381 entries, 0 to 122380
Data columns (total 44 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   country                       122381 non-null  object
 1   location_name                 122381 non-null  object
 2   latitude                      122381 non-null  float64
 3   longitude                     122381 non-null  float64
 4   timezone                      122381 non-null  object
 5   last_updated_epoch            122381 non-null  int64
 6   last_updated                  122381 non-null  datetime64[ns]
 7   temperature_celsius           122381 non-null  float64
 8   temperature_fahrenheit        122381 non-null  float64
 9   condition_text                122381 non-null  object
 10  wind_mph                      122381 non-null  float64
 11  wind_kph                      122381 non-null  float64
 12  wind_degree                   122381 non-null  int64
 13  wind_direction                122381 non-null  object
 14  pressure_mb                   122381 non-null  float64
 15  pressure_in                   122381 non-null  float64
 16  precip_mm                     122381 non-null  float64
 17  precip_in                     122381 non-null  float64
 18  humidity                      122381 non-null  int64
 19  cloud                         122381 non-null  int64
 20  feels_like_celsius            122381 non-null  float64
 21  feels_like_fahrenheit         122381 non-null  float64
 22  visibility_km                 122381 non-null  float64
 23  visibility_miles              122381 non-null  float64
 24  uv_index                      122381 non-null  float64
 25  gust_mph                      122381 non-null  float64
 26  gust_kph                      122381 non-null  float64
 27  air_quality_Carbon_Monoxide   122381 non-null  float64
 28  air_quality_Ozone             122381 non-null  float64
 29  air_quality_Nitrogen_dioxide  122381 non-null  float64
 30  air_quality_Sulphur_dioxide   122381 non-null  float64
 31  air_quality_PM2.5             122381 non-null  float64
 32  air_quality_PM10              122381 non-null  float64
 33  air_quality_us-epa-index      122381 non-null  int64
 34  air_quality_gb-defra-index    122381 non-null  int64
 35  sunrise                       122381 non-null  object
 36  sunset                        122381 non-null  object
 37  moonrise                      122381 non-null  object
 38  moonset                       122381 non-null  object
 39  moon_phase                    122381 non-null  object
 40  moon_illumination             122381 non-null  int64
 41  year                          122381 non-null  int32
 42  month                         122381 non-null  int32
 43  day                           122381 non-null  int32
dtypes: datetime64[ns](1), float64(23), int32(3), int64(7), object(10)
memory usage: 39.7+ MB

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination',
       'year', 'month', 'day'],
      dtype='object')

In [5]:
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [16]:
df.to_csv("cleaned_global_weather.csv", index=False)

In [6]:
df = df.dropna()

In [7]:
df['country'].value_counts()

country
Bulgaria         1438
Indonesia        1259
Sudan            1256
Thailand         1255
Turkey           1255
                 ...
Saudi Arabien       1
Bélgica             1
Turkménistan        1
火鸡                  1
Jemen               1
Name: count, Length: 211, dtype: int64

In [8]:
df['last_updated'] = pd.to_datetime(df['last_updated'])

df['year'] = df['last_updated'].dt.year
df['month'] = df['last_updated'].dt.month
df['day'] = df['last_updated'].dt.day

In [11]:
df[['last_updated','year','month','day']].head()

         last_updated  year  month  day
0 2024-05-16 13:15:00  2024      5   16
1 2024-05-16 10:45:00  2024      5   16
2 2024-05-16 09:45:00  2024      5   16
3 2024-05-16 10:45:00  2024      5   16
4 2024-05-16 09:45:00  2024      5   16

In [15]:
df['hour'] = df['last_updated'].dt.hour
df[['last_updated','hour']].head()

         last_updated  hour
0 2024-05-16 13:15:00    13
1 2024-05-16 10:45:00    10
2 2024-05-16 09:45:00     9
3 2024-05-16 10:45:00    10
4 2024-05-16 09:45:00     9